
SUBROUTINE STACK_ALLOC_I4_1 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

INTEGER (4), POINTER, CONTIGUOUS :: KPTR (:)
INTEGER :: LBOUNDS (1), UBOUNDS (1), ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = 1

KPTR (LBOUNDS (1):UBOUNDS (1)) => YSTACK%IDATA4 (:,YDSTACK%L4+1:YDSTACK%L4+ISIZE)
YDSTACK%L4 = YDSTACK%L4 + ISIZE
IF (YDSTACK%L4 > YDSTACK%U4) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_I4_2 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

INTEGER (4), POINTER, CONTIGUOUS :: KPTR (:,:)
INTEGER :: LBOUNDS (2), UBOUNDS (2), ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = UBOUNDS (2) - LBOUNDS (2) + 1

KPTR (LBOUNDS (1):UBOUNDS (1), LBOUNDS (2):UBOUNDS (2)) => YSTACK%IDATA4 (:,YDSTACK%L4+1:YDSTACK%L4+ISIZE)
YDSTACK%L4 = YDSTACK%L4 + ISIZE
IF (YDSTACK%L4 > YDSTACK%U4) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_L4_1 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

LOGICAL (4), POINTER, CONTIGUOUS :: KPTR (:)
INTEGER :: LBOUNDS (1), UBOUNDS (1), ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = 1

KPTR (LBOUNDS (1):UBOUNDS (1)) => YSTACK%LDATA4 (:,YDSTACK%L4+1:YDSTACK%L4+ISIZE)
YDSTACK%L4 = YDSTACK%L4 + ISIZE
IF (YDSTACK%L4 > YDSTACK%U4) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_L4_2 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

LOGICAL (4), POINTER, CONTIGUOUS :: KPTR (:,:)
INTEGER :: LBOUNDS (2), UBOUNDS (2), ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = UBOUNDS (2) - LBOUNDS (2) + 1

KPTR (LBOUNDS (1):UBOUNDS (1), LBOUNDS (2):UBOUNDS (2)) => YSTACK%LDATA4 (:,YDSTACK%L4+1:YDSTACK%L4+ISIZE)
YDSTACK%L4 = YDSTACK%L4 + ISIZE
IF (YDSTACK%L4 > YDSTACK%U4) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_R8_1 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

REAL (8), POINTER, CONTIGUOUS :: KPTR (:)
INTEGER :: LBOUNDS (1), UBOUNDS (1), ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = 1

KPTR (LBOUNDS (1):UBOUNDS (1)) => YSTACK%ZDATA8 (:,YDSTACK%L8+1:YDSTACK%L8+ISIZE)
YDSTACK%L8 = YDSTACK%L8 + ISIZE
IF (YDSTACK%L8 > YDSTACK%U8) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_R8_2 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

REAL (8), POINTER, CONTIGUOUS :: KPTR (:,:)
INTEGER :: LBOUNDS (2), UBOUNDS (2), ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = UBOUNDS (2) - LBOUNDS (2) + 1

KPTR (LBOUNDS (1):UBOUNDS (1), LBOUNDS (2):UBOUNDS (2)) => YSTACK%ZDATA8 (:,YDSTACK%L8+1:YDSTACK%L8+ISIZE)
YDSTACK%L8 = YDSTACK%L8 + ISIZE
IF (YDSTACK%L8 > YDSTACK%U8) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

