MODULE STACK_MOD

USE PARKIND1, ONLY : JPRB, JPIM, JPIA
USE ABOR1_ACC_MOD

IMPLICIT NONE

TYPE STACK_DATA
  REAL    (KIND=4), POINTER, CONTIGUOUS :: ZDATA4 (:,:)
  INTEGER (KIND=4), POINTER, CONTIGUOUS :: IDATA4 (:,:)
  LOGICAL (KIND=4), POINTER, CONTIGUOUS :: LDATA4 (:,:)
  REAL    (KIND=8), POINTER, CONTIGUOUS :: ZDATA8 (:,:)
END TYPE

TYPE STACK
  INTEGER*4 :: L4
  INTEGER*4 :: U4
  INTEGER*4 :: L8
  INTEGER*4 :: U8
END TYPE

TYPE (STACK_DATA) :: YSTACK

PUBLIC :: STACK, YSTACK

!$OMP DECLARE TARGET (YSTACK)

END
